### ISSUE TITLE
is the config option (-c) broken?

### ISSUE THREAD

**Issue by mreinstein** [jscrambler/node-jscrambler#30]
Here's my command:

```bash
 ./node_modules/jscrambler/bin/jscrambler level-editor.js -o test.js -c jscrambler.json 
```

here's my jscrambler.json:

```javascript
{
  "browser_os_lock": "chrome",
  "dead_code": "%DEFAULT%",
  "dictionary_compression": "%DEFAULT%",
  "domain_lock": "plasma.s3-website-us-east-1.amazonaws.com",
  "dot_notation_elimination": "%DEFAULT%",
  "function_outlining": "%DEFAULT%",
  "function_reorder": "%DEFAULT%",
  "member_enumeration": "%DEFAULT%",
  "mode": "html5",
  "rename_local": "%DEFAULT%",
  "self_defending": "%DEFAULT%",
  "whitespace": "%DEFAULT%"
}
```

when I run the command I get a build, but several options are not enabled. For example self defending. What gives?

**Comment by mreinstein** [comment]
It seems to work in 0.6.1, and 0.6.5. I'm assuming something broke it in 0.6.6.

It's getting irritating seeing patch releases break my production deploy process. :-1:

**Comment by mreinstein** [comment]
I'm wrong, 0.6.5 is broken too. the last working build for me is 0.6.1

**Comment by mreinstein** [comment]
> That JSON structure was deprecated on v0.6.0

It would be better to not break API in minor or patch releases. I realize that anything < 1.0.0 is considered  unstable but practically, people are already using this in their live code.


Here is how you could fix this: 

add a check that looks to see if the `params` attribute is present. If it's missing and there are options directly on the config object, load them, and print a deprecation warning to the console.

This would allow existing code to keep working, but also give people notification that the code has changed, and to update.

When you cut a `1.0.0` release you're allowed to make breaking API changes, and you could throw out all these crufty bits.

**Comment by magalhas** [comment]
`npm` considers minor versions of modules < 1.0.0 as major. But yes, I agree with your deprecation notices in the console, most good libs do that (I'm thinking of React at the moment).
