### ISSUE TITLE
infrastructure simplification/expanded testing

### ISSUE THREAD

**Issue by mreinstein** [jscrambler/node-jscrambler#31]
I'm willing to spend time expanding the test suite a bit, but in doing so I would do some things a little differently.
1. replace grunt with plain ole'  `npm run` http://substack.net/task_automation_with_npm_run
2. simplify the testing infrastucture, replacing jasmine with https://github.com/isaacs/node-tap

thoughts?

**Comment by magalhas** [comment]
I'm ok with letting Grunt go away, it'll make the module a lot faster to install.

Considering tap, I've never used it. Lately I've been using Mocha, Sinon and Chai, but it's all "the same" considering that the number of specs won't grow much. Current suites need to be migrated though.

**Comment by mreinstein** [comment]
sorry, your product is way too expensive, I've moved on to more reasonably priced obfuscation solutions. That said, these code changes are probably a good idea.

btw, it's also kind of annoying that your pricing page doesn't even list prices https://jscrambler.com/pricing
