### ISSUE TITLE
param mode not working ?

### ISSUE THREAD

**Issue by michabbb** [jscrambler/node-jscrambler#33]
hi, don´t know if this is a web api thing or a bug of this project.
everytime a upload files with a mode, the mode (blue label) does not appear in the jscrambler project web-frontend... so in fact i don´t know if mode is really sent...i tried via config and cli parameter...
in every case the mode label is missing...

**Comment by michabbb** [comment]
It's a bug of the Frontend, here's a statement from the support:

  Hi,

I've tested it and the application mode is applied but for some reason the Website is not showing it. The issue has been reported and as soon as it is fixed we'll let you know.

Thank you.

**Comment by michabbb** [comment]
Update from the support:

Hi,

Just to let you know that the problem has been fixed though the problem was indeed related with the Web API not considering the application mode and not a problem with the Website interface not displaying it.

Thank you.

**Comment by magalhas** [comment]
Glad everything is fine as of now :+1:
