### ISSUE TITLE
nodejs requires all methods of lodash as a separate module

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [jscrambler/node-jscrambler#34]
After installing jscrambler with it's dependencies I can't get the code running. I am getting errors like this:

> Cannot find module 'lodash.**_createwrapper**'

After installing lodash.**_createwrapper** it says:

> Cannot find module 'lodash.**_keyprefix**'

then  lodash.**_objectpool**, then lodash.**_isnative**, then lodash.**_slice** and so on.

**Comment by magalhas** [comment]
That looks like an interrupted installation. Please try to remove `node_modules` directory and running `npm install` again.

**Comment by Serhiy-Shekhovtsov** [comment]
Tried and it didn't help. By the end I have installed all methods one by one. It was like 20 different modules.

**Comment by magalhas** [comment]
That's very odd since no one else is facing the same problem. Are you using the HEAD of the repository or the latest published version on npm?

**Comment by Serhiy-Shekhovtsov** [comment]
I used this command to install:
> npm install jscrambler

**Comment by magalhas** [comment]
I've just did ran following test without facing any issues:
```
cd ~/Desktop
mkdir test
cd test
npm install jscrambler
```

**Comment by Serhiy-Shekhovtsov** [comment]
The installation was successfull, but when I tried to run jScrambler I was getting those errors.
