### ISSUE TITLE
API request hangs in case of error

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [jscrambler/node-jscrambler#35]
When using Upload/download example you provided, in case of obfuscation error the process just silently hangs untli you kill it.
The error I am getting Error (code **-313**) and have no idea what that means.

I put this logging information:

```
      .then(function (res) {
         console.log("downloading files");
         return jScrambler.downloadCode(client, res.id);
      })
```

and I can see "downloading files" in the console, this is a last message and after it there is no anything else.

**Comment by magalhas** [comment]
Can you please contact JScrambler's support? The problem appears to be in the services side and not in the client.

**Comment by Serhiy-Shekhovtsov** [comment]
Hi José, sorry for late response. I think it would be really cool to have some timeout option on a client side, so it will not hang forever.
