### ISSUE TITLE
output files to directory is not working correctly

### ISSUE THREAD

**Issue by narainsagar** [jscrambler/node-jscrambler#39]
The issue is when I execute a command: 
```
jscrambler dist/*.js -o dist/temp/ -c ./jscrambler.config.json
```

It doesn't write files into correct path, it creates new directories under `dist/` as `dist/dist/temp`. Thus it should have to create `dist/temp`..

**Comment by magalhas** [comment]
This client is deprecated. You should use https://github.com/jscrambler/javascript-jscrambler instead

**Comment by magalhas** [comment]
By the way what you've described is the intended behaviour. You've got the `cwd` parameter to overcome that.
